[package]
name = "xin_os_rust_boilerplate"
version = "0.1.0"
authors = ["Martin Loffler <git@fatalerrorcoded.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["staticlib"]

[dependencies]
